import { Item, UserProfile } from './types';

// ─── Verified Unsplash image pool ────────────────────────────────────────────
// Every URL below has been visually confirmed to show the described clothing.
const IMGS = {
  // Tops — tees, shirts, polos, crewnecks
  tops: [
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700', // white tee / hoodie
    'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=700', // classic casual top
    'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=700',    // white button-up shirt
    'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=700', // polo shirt
    'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=700', // graphic / print tee
    'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=700',    // black hoodie
    'https://images.unsplash.com/photo-1617952385804-7b326fa42c30?w=700', // coloured crewneck
  ],
  // Hoodies — streetwear & minimal oversized
  hoodies: [
    'https://images.unsplash.com/photo-1564557287817-3785e38ec1f5?w=700', // beige oversized hoodie
    'https://images.unsplash.com/photo-1609873814058-a8928924184a?w=700', // yellow skull graphic hoodie
    'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=700', // tan hoodie rear view
    'https://images.unsplash.com/photo-1615397587950-3cbb55f95b77?w=700', // white clean hoodie
  ],
  // Knitwear — sweaters, cardigans
  knitwear: [
    'https://images.unsplash.com/photo-1601379327928-bedfaf9da2d0?w=700', // stacked grey/beige knits
    'https://images.unsplash.com/photo-1600369672890-ac00f1907858?w=700', // stacked teal/green knits
  ],
  // Bottoms — jeans, trousers, shorts
  bottoms: [
    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=700', // indigo straight denim
    'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=700', // coloured trousers
    'https://images.unsplash.com/photo-1475178626620-a4d074967452?w=700', // casual chino
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=700', // relaxed pants
    'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=700',    // black cargo pants
  ],
  // Denim jackets
  denim: [
    'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=700', // dark denim jacket on hanger
    'https://images.unsplash.com/photo-1555583743-991174c11425?w=700',    // man in blue denim jacket
    'https://images.unsplash.com/photo-1556041068-5874261f23e5?w=700',    // woman in light denim jacket
  ],
  // Shoes — sneakers, boots, sandals
  shoes: [
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700',    // Nike classic red
    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=700', // sneakers overhead
    'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=700',    // colourful retro sneakers
    'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=700', // trail / running shoe
    'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=700', // clean white sneakers
  ],
  // Outerwear — jackets, coats, fleeces
  outerwear: [
    'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=700', // structured coat
    'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=700', // leather / moto jacket
    'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700',    // trench coat
    'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=700', // puffer jacket navy
    'https://images.unsplash.com/photo-1608113562252-b320e7628e17?w=700', // burgundy puffer street
    'https://images.unsplash.com/photo-1621343342490-b0ab42b7fcdb?w=700', // cream puffer with boots
  ],
  // Accessories — bags, watches, jewellery
  accessories: [
    'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=700', // watch flat lay
    'https://images.unsplash.com/photo-1611923134239-b9be5816b23e?w=700', // structured handbag
    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=700',    // canvas / nylon backpack
    'https://images.unsplash.com/photo-1589363358751-ab05797e5629?w=700', // luxury bag + coat flat lay
    'https://images.unsplash.com/photo-1575202332411-b01fe9ace7a8?w=700', // pale blue mini bag
  ],
  // Dresses & skirts
  dresses: [
    'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=700', // editorial slip dress
    'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=700', // flowy maxi dress
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=700', // elegant fashion dress
    'https://images.unsplash.com/photo-1618244965061-1d27b208d6e8?w=700', // camel coat + midi skirt
    'https://images.unsplash.com/photo-1575633625496-e330445f63b2?w=700', // yellow linen set
  ],
};

// ─── Seed sellers ─────────────────────────────────────────────────────────────
export interface SeedSeller {
  id: string;
  name: string;
  avatar: string;
  bio: string;
}

export const SEED_SELLERS: SeedSeller[] = [
  { id: 'seed_u01', name: 'Jordan Kim',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=jordankim`,      bio: 'Streetwear curator. NYC.' },
  { id: 'seed_u02', name: 'Tyler Brooks',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=tylerbrooks`,    bio: 'Sneakerhead. Off-White collector.' },
  { id: 'seed_u03', name: 'Sam Wallace',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=samwallace`,     bio: 'Archive streetwear. LA.' },
  { id: 'seed_u04', name: 'Devon Chen',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=devonchen`,      bio: 'Technical gear & techwear.' },
  { id: 'seed_u05', name: 'Alex Torres',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=alextorres`,     bio: 'Workwear & utility obsessed.' },
  { id: 'seed_u06', name: 'Marcus Liu',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=marcusliu`,      bio: 'Hype reseller. Chicago.' },
  { id: 'seed_u07', name: 'Priya Mehta',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=priyamehta`,     bio: 'Minimalist wardrobe, big resale.' },
  { id: 'seed_u08', name: 'Nia Johnson',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=niajohnson`,     bio: 'Luxury consignment. London.' },
  { id: 'seed_u09', name: 'Chloe Hammond',   avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=chloehammond`,   bio: 'Vintage leather & moto. Portland.' },
  { id: 'seed_u10', name: 'Maya Rivera',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=mayarivera`,     bio: 'Japanese brands & Lemaire.' },
  { id: 'seed_u11', name: 'Reed Hayes',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=reedhayes`,      bio: 'Ivy league prep. Boston.' },
  { id: 'seed_u12', name: 'Cameron Tran',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=camerontran`,    bio: 'Deadstock vintage. Bay Area.' },
  { id: 'seed_u13', name: 'Lea Novak',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=leanovak`,       bio: "Denim & '90s silhouettes." },
  { id: 'seed_u14', name: 'Sam Williams',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=samwilliams`,    bio: 'Champion & classic American.' },
  { id: 'seed_u15', name: 'Felix Ortega',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=felixortega`,    bio: 'CDG & avant-garde. Tokyo.' },
  { id: 'seed_u16', name: 'Mia Fischer',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=miafischer`,     bio: 'Kapital & artisanal pieces.' },
  { id: 'seed_u17', name: 'Omar Khalil',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=omarkhalil`,     bio: 'Cashmere & Italian luxury.' },
  { id: 'seed_u18', name: 'Zoe Park',        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=zoepark`,        bio: 'Adidas archive. Seoul.' },
  { id: 'seed_u19', name: 'Jess Rodriguez',  avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=jessrodriguez`,  bio: 'Gorpcore & trail running.' },
  { id: 'seed_u20', name: 'Ben Adams',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=benadams`,       bio: 'Jordan & Nike collector.' },
  { id: 'seed_u21', name: 'Kai Wong',        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=kaiwong`,        bio: 'Clean fits only. SF.' },
  { id: 'seed_u22', name: 'Ari Santos',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=arisantos`,      bio: "Arc'teryx & technical shells." },
  { id: 'seed_u23', name: 'Dana Kowalski',   avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=danakowalski`,   bio: 'Patagonia & outdoor life.' },
  { id: 'seed_u24', name: 'Leo Barrera',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=leobarrera`,     bio: 'Stone Island & menswear.' },
  { id: 'seed_u25', name: 'Iris Martinez',   avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=irismartinez`,   bio: 'Country & classic British.' },
  { id: 'seed_u26', name: 'Tara Osei',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=taraosei`,       bio: 'Vintage bags & jewellery.' },
  { id: 'seed_u27', name: 'Nora Chen',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=norachen`,       bio: 'Reformation & sustainable brands.' },
  { id: 'seed_u28', name: 'Kim Anderson',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=kimanderson`,    bio: 'Ethical & handmade fashion.' },
  { id: 'seed_u29', name: 'Sol Benali',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=solbenali`,      bio: 'Minimalist jewellery & accessories.' },
  { id: 'seed_u30', name: 'Evan Peters',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=evanpeters`,     bio: 'Watch & menswear collector.' },
  { id: 'seed_u31', name: 'Vera Liu',        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=veraliu`,        bio: 'Prada & designer re-sale.' },
  { id: 'seed_u32', name: 'Jake Ndiaye',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=jakendiaye`,     bio: 'Fitted hats & streetwear.' },
  { id: 'seed_u33', name: 'Pat O\'Brien',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=patobrien`,      bio: 'Japanese label obsessive.' },
  { id: 'seed_u34', name: 'Quinn Adams',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=quinnadams`,     bio: 'Basics done right.' },
  { id: 'seed_u35', name: 'Maya Ross',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=mayaross`,       bio: 'Acne & Scandinavian minimalism.' },
  { id: 'seed_u36', name: 'Rob Santos',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=robsantos`,      bio: 'Polo collection & classic RL.' },
  { id: 'seed_u37', name: 'Lily Chai',       avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=lilychai`,       bio: 'Issey Miyake & Japanese avant-garde.' },
  { id: 'seed_u38', name: 'Tim Barnes',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=timbarnes`,      bio: 'Workwear essentials. Detroit.' },
  { id: 'seed_u39', name: 'Jo Huang',        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=johuang`,        bio: 'Luxury trousers & tailoring.' },
  { id: 'seed_u40', name: 'Wren Ahmad',      avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=wrenahmad`,      bio: 'Chinos and clean casual.' },
  { id: 'seed_u41', name: 'Blake Morris',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=blakemorris`,    bio: 'Birkenstocks & slow fashion.' },
  { id: 'seed_u42', name: 'Finn Kowalski',   avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=finnkowalski`,   bio: 'Skate shoes & skate culture.' },
  { id: 'seed_u43', name: 'Dani Reeves',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=danireeves`,     bio: 'Boots & British classics.' },
  { id: 'seed_u44', name: 'Sage Wu',         avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=sagewu`,         bio: 'Gorpcore & mountain style.' },
  { id: 'seed_u45', name: 'Nico Ferrari',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=nicoferrari`,    bio: 'Suicoke & Italian casual.' },
  { id: 'seed_u46', name: 'Elle Johansson',  avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=ellejohansson`,  bio: 'Scandi minimalism & Toteme.' },
  { id: 'seed_u47', name: 'Remy Dubois',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=remydubois`,     bio: 'Rick Owens & avant-garde. Paris.' },
  { id: 'seed_u48', name: 'Yuki Tanaka',     avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=yukitanaka`,     bio: 'Vintage Americana. Tokyo.' },
  { id: 'seed_u49', name: 'Amara Okafor',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=amaraokafor`,    bio: 'Farm Rio & bold prints.' },
  { id: 'seed_u50', name: 'Lena Fischer',    avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=lenafischer`,    bio: 'COS & European minimalism.' },
];

// Quick lookup: id → name
const S = Object.fromEntries(SEED_SELLERS.map(s => [s.id, s.name]));

type SeedItem = Omit<Item, 'id' | 'createdAt'>;

// ─── Seed items ───────────────────────────────────────────────────────────────
// 85 items covering all 6 style dimensions (outdoor, streetwear, luxury,
// minimal, preppy, vintage) × 6 categories × 4 price tiers.
// Deliberately varied so the recommendation algorithm has enough signal to
// separate distinct taste profiles.

const items: SeedItem[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // STREETWEAR / HYPE (11 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u01', sellerName: S['seed_u01'],
    title: 'Supreme Box Logo Crewneck FW22 — Red L',
    description: 'Worn once, shipped in original poly bag. Bogo red, size L. Fits true.',
    price: 285,
    images: [IMGS.tops[5]],
    category: 'tops', subcategory: 'crewneck',
    styles: ['streetwear', 'hypebeast'], colors: ['red'],
    size: 'L', brand: 'Supreme', condition: 'like_new',
    priceRange: 3, likes: 634, views: 4100, sold: false,
  },
  {
    sellerId: 'seed_u02', sellerName: S['seed_u02'],
    title: 'Off-White Industrial Belt SS19 — Yellow/Black',
    description: 'Slight wear on the hardware — buckle shows light brass patina. Iconic.',
    price: 95,
    images: [IMGS.accessories[2]],
    category: 'accessories', subcategory: 'belts',
    styles: ['streetwear', 'luxury'], colors: ['yellow', 'black'],
    size: 'one size', brand: 'Off-White', condition: 'good',
    priceRange: 2, likes: 412, views: 2340, sold: false,
  },
  {
    sellerId: 'seed_u03', sellerName: S['seed_u03'],
    title: 'Stüssy 8-Ball Fleece Crewneck — Black L',
    description: 'Heavy 420-gsm fleece, dropped shoulders, barely washed.',
    price: 110,
    images: [IMGS.tops[6]],
    category: 'tops', subcategory: 'crewneck',
    styles: ['streetwear', 'vintage'], colors: ['black'],
    size: 'L', brand: 'Stüssy', condition: 'like_new',
    priceRange: 2, likes: 305, views: 1870, sold: false,
  },
  {
    sellerId: 'seed_u04', sellerName: S['seed_u04'],
    title: 'Nike ACG Storm-FIT Jacket — Black M',
    description: 'Full zip, DWR coated, side entry pockets, adjustable hem.',
    price: 145,
    images: [IMGS.outerwear[3]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['streetwear', 'techwear', 'outdoor'], colors: ['black'],
    size: 'M', brand: 'Nike ACG', condition: 'like_new',
    priceRange: 2, likes: 278, views: 1640, sold: false,
  },
  {
    sellerId: 'seed_u05', sellerName: S['seed_u05'],
    title: 'Carhartt WIP Double Knee Pant — Stone W32 L30',
    description: 'Duck canvas, stone washed. The workwear pant that outhypes Supreme.',
    price: 95,
    images: [IMGS.bottoms[1]],
    category: 'bottoms', subcategory: 'pants',
    styles: ['streetwear', 'workwear', 'utility'], colors: ['stone', 'tan'],
    size: 'W32 L30', brand: 'Carhartt WIP', condition: 'good',
    priceRange: 2, likes: 88, views: 542, sold: false,
  },
  {
    sellerId: 'seed_u06', sellerName: S['seed_u06'],
    title: 'Corteiz Alcatraz Jacket — Navy XL',
    description: 'CRTZ drop exclusive. Size XL, hard to find. Tag still attached.',
    price: 320,
    images: [IMGS.outerwear[0]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['streetwear', 'hypebeast'], colors: ['navy'],
    size: 'XL', brand: 'Corteiz', condition: 'like_new',
    priceRange: 3, likes: 891, views: 5200, sold: false,
  },
  {
    sellerId: 'seed_u33', sellerName: S['seed_u33'],
    title: 'Palace Tri-Ferg Tee FW23 — White M',
    description: 'Classic embroidered tri-ferg chest logo. 100% cotton. Worn twice.',
    price: 65,
    images: [IMGS.tops[4]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['streetwear', 'skate'], colors: ['white'],
    size: 'M', brand: 'Palace', condition: 'like_new',
    priceRange: 1, likes: 198, views: 1240, sold: false,
  },
  {
    sellerId: 'seed_u06', sellerName: S['seed_u06'],
    title: 'KITH Box Logo Hoodie — Black L',
    description: 'Classic KITH serif box logo. 580-gsm fleece. Barely worn.',
    price: 165,
    images: [IMGS.hoodies[0]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['streetwear', 'minimal'], colors: ['black'],
    size: 'L', brand: 'KITH', condition: 'like_new',
    priceRange: 3, likes: 310, views: 1890, sold: false,
  },
  {
    sellerId: 'seed_u20', sellerName: S['seed_u20'],
    title: 'Nike SB Dunk Low Pro — Blue Jay/White 10',
    description: 'DS pair from 2021. Box slightly damaged but shoe is perfect.',
    price: 185,
    images: [IMGS.shoes[1]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['streetwear', 'skate'], colors: ['blue', 'white'],
    size: '10', brand: 'Nike', condition: 'new',
    priceRange: 3, likes: 544, views: 3300, sold: false,
  },
  {
    sellerId: 'seed_u03', sellerName: S['seed_u03'],
    title: 'Sp5der Worldwide Web Hoodie — Pink L',
    description: 'FW23 spider web print. Rhinestone accents, barely worn.',
    price: 175,
    images: [IMGS.hoodies[1]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['streetwear', 'hypebeast'], colors: ['pink'],
    size: 'L', brand: 'Sp5der', condition: 'like_new',
    priceRange: 3, likes: 421, views: 2600, sold: false,
  },
  {
    sellerId: 'seed_u24', sellerName: S['seed_u24'],
    title: 'Stone Island Garment-Dyed Overshirt — Khaki L',
    description: 'Compass badge, button placket. One of the cleanest SI pieces.',
    price: 280,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'overshirt',
    styles: ['streetwear', 'luxury', 'workwear'], colors: ['khaki', 'olive'],
    size: 'L', brand: 'Stone Island', condition: 'good',
    priceRange: 3, likes: 334, views: 2010, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MINIMAL / CLEAN (12 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u07', sellerName: S['seed_u07'],
    title: 'COS Oversized Linen Shirt — Cream M',
    description: 'Relaxed fit, 100% linen. Barely worn — still crisp.',
    price: 48,
    images: [IMGS.tops[2]],
    category: 'tops', subcategory: 'shirts',
    styles: ['minimal', 'casual'], colors: ['white', 'cream'],
    size: 'M', brand: 'COS', condition: 'like_new',
    priceRange: 1, likes: 134, views: 890, sold: false,
  },
  {
    sellerId: 'seed_u08', sellerName: S['seed_u08'],
    title: 'Toteme Scarf Coat — Camel 36',
    description: 'The iconic scarf-collar wool coat. Camel, size 36. Dry-cleaned.',
    price: 480,
    images: [IMGS.outerwear[2]],
    category: 'outerwear', subcategory: 'coat',
    styles: ['minimal', 'luxury'], colors: ['camel', 'tan'],
    size: '36', brand: 'Toteme', condition: 'like_new',
    priceRange: 4, likes: 521, views: 3200, sold: false,
  },
  {
    sellerId: 'seed_u09', sellerName: S['seed_u09'],
    title: 'Arket Merino Polo — Navy M',
    description: 'Fine merino rib, washed a handful of times. Holds its shape perfectly.',
    price: 62,
    images: [IMGS.tops[1]],
    category: 'tops', subcategory: 'polo',
    styles: ['minimal', 'preppy'], colors: ['navy'],
    size: 'M', brand: 'Arket', condition: 'good',
    priceRange: 1, likes: 97, views: 590, sold: false,
  },
  {
    sellerId: 'seed_u10', sellerName: S['seed_u10'],
    title: 'Lemaire Straight-Leg Trousers — Ecru 46',
    description: 'Wool-blend, single pleat front. The perfect drape. Size 46 EU.',
    price: 220,
    images: [IMGS.bottoms[2]],
    category: 'bottoms', subcategory: 'trousers',
    styles: ['minimal', 'luxury'], colors: ['ecru', 'beige'],
    size: '46', brand: 'Lemaire', condition: 'good',
    priceRange: 3, likes: 302, views: 1780, sold: false,
  },
  {
    sellerId: 'seed_u35', sellerName: S['seed_u35'],
    title: 'Acne Studios Logo Hoodie — Dusty Pink S',
    description: 'Classic face logo. 500-gsm, dusty pink. One season, washed once.',
    price: 185,
    images: [IMGS.tops[5]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['minimal', 'luxury'], colors: ['pink', 'dusty rose'],
    size: 'S', brand: 'Acne Studios', condition: 'like_new',
    priceRange: 3, likes: 301, views: 1890, sold: false,
  },
  {
    sellerId: 'seed_u37', sellerName: S['seed_u37'],
    title: 'Issey Miyake Pleats Please Top — Black OS',
    description: 'Permanent pleat technology, machine washable, never wrinkles.',
    price: 145,
    images: [IMGS.tops[1]],
    category: 'tops', subcategory: 'tops',
    styles: ['minimal', 'avant garde', 'japanese'], colors: ['black'],
    size: 'one size', brand: 'Issey Miyake', condition: 'good',
    priceRange: 2, likes: 234, views: 1380, sold: false,
  },
  {
    sellerId: 'seed_u34', sellerName: S['seed_u34'],
    title: 'Hanes Beefy-T 3-Pack — White M (NWT)',
    description: 'The go-to blank tee. Still factory folded, polybag intact.',
    price: 22,
    images: [IMGS.tops[0]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['minimal', 'casual'], colors: ['white'],
    size: 'M', brand: 'Hanes', condition: 'new',
    priceRange: 0, likes: 67, views: 410, sold: false,
  },
  {
    sellerId: 'seed_u50', sellerName: S['seed_u50'],
    title: 'Uniqlo Soufflé Knit Turtleneck — Oatmeal M',
    description: 'Incredibly soft Soufflé yarn. Worn three times. Oatmeal beige.',
    price: 28,
    images: [IMGS.knitwear[0]],
    category: 'tops', subcategory: 'knitwear',
    styles: ['minimal', 'casual'], colors: ['oatmeal', 'beige'],
    size: 'M', brand: 'Uniqlo', condition: 'like_new',
    priceRange: 0, likes: 112, views: 680, sold: false,
  },
  {
    sellerId: 'seed_u29', sellerName: S['seed_u29'],
    title: 'Everlane Day Tote — Canvas Natural',
    description: 'Thick cotton canvas. Natural colour. Some light soil on base.',
    price: 38,
    images: [IMGS.accessories[1]],
    category: 'accessories', subcategory: 'bags',
    styles: ['minimal', 'casual'], colors: ['natural', 'cream'],
    size: 'one size', brand: 'Everlane', condition: 'good',
    priceRange: 0, likes: 84, views: 490, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: 'Norse Projects Alan Oxford Shirt — Light Blue M',
    description: 'Classic GOTS cotton Oxford. Light blue, Mother-of-pearl buttons.',
    price: 88,
    images: [IMGS.tops[2]],
    category: 'tops', subcategory: 'shirts',
    styles: ['minimal', 'preppy'], colors: ['light blue', 'blue'],
    size: 'M', brand: 'Norse Projects', condition: 'like_new',
    priceRange: 2, likes: 178, views: 1040, sold: false,
  },
  {
    sellerId: 'seed_u27', sellerName: S['seed_u27'],
    title: 'Reformation Etta Slip Dress — Ivory XS',
    description: 'Satin, bias cut, adjustable spaghetti straps. Barely worn.',
    price: 95,
    images: [IMGS.dresses[0]],
    category: 'dresses', subcategory: 'slip dress',
    styles: ['minimal', 'elegant'], colors: ['ivory', 'white'],
    size: 'XS', brand: 'Reformation', condition: 'like_new',
    priceRange: 2, likes: 267, views: 1540, sold: false,
  },
  {
    sellerId: 'seed_u07', sellerName: S['seed_u07'],
    title: 'Silk Slip Dress — Forest Green S',
    description: 'Bias cut, adjustable straps. Deep forest green. Dry-clean only.',
    price: 78,
    images: [IMGS.dresses[2]],
    category: 'dresses', subcategory: 'slip dress',
    styles: ['minimal', 'elegant', 'y2k'], colors: ['green', 'forest green'],
    size: 'S', brand: 'Zara', condition: 'like_new',
    priceRange: 1, likes: 224, views: 1100, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // LUXURY / DESIGNER (10 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u08', sellerName: S['seed_u08'],
    title: 'Maison Margiela Tabi Boots — Black 38',
    description: 'Iconic split-toe. Stacked heel. Some heel wear — priced accordingly.',
    price: 480,
    images: [IMGS.shoes[2]],
    category: 'shoes', subcategory: 'boots',
    styles: ['luxury', 'avant garde'], colors: ['black'],
    size: '38', brand: 'Maison Margiela', condition: 'fair',
    priceRange: 4, likes: 521, views: 3200, sold: false,
  },
  {
    sellerId: 'seed_u15', sellerName: S['seed_u15'],
    title: 'CDG SHIRT × Lacoste Polo — White/Red M',
    description: 'Collab CDG heart on the chest, Lacoste crocodile on the sleeve.',
    price: 95,
    images: [IMGS.tops[3]],
    category: 'tops', subcategory: 'polo',
    styles: ['luxury', 'preppy', 'streetwear'], colors: ['white', 'red'],
    size: 'M', brand: 'Comme des Garçons', condition: 'like_new',
    priceRange: 2, likes: 447, views: 2700, sold: false,
  },
  {
    sellerId: 'seed_u16', sellerName: S['seed_u16'],
    title: 'Kapital Boro Ring Coat — Blue/Patchwork 2',
    description: 'Patchwork denim Boro construction. Very unique. Size 2 (M–L).',
    price: 650,
    images: [IMGS.denim[0]],
    category: 'outerwear', subcategory: 'coat',
    styles: ['luxury', 'vintage', 'japanese', 'avant garde'], colors: ['blue', 'multicolor'],
    size: '2', brand: 'Kapital', condition: 'good',
    priceRange: 4, likes: 367, views: 2200, sold: false,
  },
  {
    sellerId: 'seed_u17', sellerName: S['seed_u17'],
    title: 'Loro Piana Cashmere Crewneck — Ivory 50',
    description: 'Baby cashmere. Italian-made. Size 50 EU. Extremely soft.',
    price: 395,
    images: [IMGS.knitwear[0]],
    category: 'tops', subcategory: 'knitwear',
    styles: ['luxury', 'minimal'], colors: ['ivory', 'cream'],
    size: '50', brand: 'Loro Piana', condition: 'good',
    priceRange: 4, likes: 188, views: 1120, sold: false,
  },
  {
    sellerId: 'seed_u31', sellerName: S['seed_u31'],
    title: 'Prada Re-Edition 2005 Re-Nylon Bag — Black',
    description: 'Re-nylon, triangle logo, authenticity card included. Barely used.',
    price: 650,
    images: [IMGS.accessories[3]],
    category: 'accessories', subcategory: 'bags',
    styles: ['luxury', 'minimal', 'y2k'], colors: ['black'],
    size: 'one size', brand: 'Prada', condition: 'like_new',
    priceRange: 4, likes: 812, views: 5100, sold: false,
  },
  {
    sellerId: 'seed_u08', sellerName: S['seed_u08'],
    title: 'Bottega Veneta Cassette Mini — Khaki',
    description: 'Intreccio weave, two-way zip, shoulder strap. Comes with dust bag.',
    price: 980,
    images: [IMGS.accessories[4]],
    category: 'accessories', subcategory: 'bags',
    styles: ['luxury', 'minimal'], colors: ['khaki', 'green'],
    size: 'one size', brand: 'Bottega Veneta', condition: 'like_new',
    priceRange: 4, likes: 676, views: 4200, sold: false,
  },
  {
    sellerId: 'seed_u47', sellerName: S['seed_u47'],
    title: 'Rick Owens DRKSHDW Cargo Pant — Black M',
    description: 'Asymmetric hem, thigh pocket, drawstring ankle. Signature Rick silhouette.',
    price: 345,
    images: [IMGS.bottoms[4]],
    category: 'bottoms', subcategory: 'pants',
    styles: ['luxury', 'avant garde', 'minimal'], colors: ['black'],
    size: 'M', brand: 'Rick Owens', condition: 'good',
    priceRange: 3, likes: 289, views: 1760, sold: false,
  },
  {
    sellerId: 'seed_u39', sellerName: S['seed_u39'],
    title: 'Loro Piana Tasche Wool Trousers — Charcoal 48',
    description: 'Superfine wool, single pleat, belt loops. Incredibly refined.',
    price: 340,
    images: [IMGS.bottoms[1]],
    category: 'bottoms', subcategory: 'trousers',
    styles: ['luxury', 'minimal'], colors: ['charcoal', 'grey'],
    size: '48', brand: 'Loro Piana', condition: 'like_new',
    priceRange: 4, likes: 145, views: 880, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: 'Jacquemus La Chemise Bari — Lilac S',
    description: 'Linen-blend, cinched waist tie. Lilac. Worn once to dinner.',
    price: 148,
    images: [IMGS.dresses[4]],
    category: 'tops', subcategory: 'shirts',
    styles: ['luxury', 'minimal', 'feminine'], colors: ['lilac', 'purple'],
    size: 'S', brand: 'Jacquemus', condition: 'like_new',
    priceRange: 2, likes: 378, views: 2240, sold: false,
  },
  {
    sellerId: 'seed_u45', sellerName: S['seed_u45'],
    title: 'Dries Van Noten Floral Overshirt — Multi M',
    description: 'SS22 floral print on heavyweight cotton. Very editorial.',
    price: 295,
    images: [IMGS.tops[4]],
    category: 'tops', subcategory: 'shirts',
    styles: ['luxury', 'editorial', 'avant garde'], colors: ['multicolor', 'floral'],
    size: 'M', brand: 'Dries Van Noten', condition: 'good',
    priceRange: 3, likes: 233, views: 1450, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // OUTDOOR / GORPCORE (9 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u22', sellerName: S['seed_u22'],
    title: "Arc'teryx Beta LT Shell — Neptune Blue M",
    description: 'Gore-Tex 3L, WaterTight zip, pit zips. Neptune blue. Barely used.',
    price: 380,
    images: [IMGS.outerwear[3]],
    category: 'outerwear', subcategory: 'shell jacket',
    styles: ['outdoor', 'techwear', 'minimal'], colors: ['blue', 'navy'],
    size: 'M', brand: "Arc'teryx", condition: 'like_new',
    priceRange: 4, likes: 298, views: 1780, sold: false,
  },
  {
    sellerId: 'seed_u23', sellerName: S['seed_u23'],
    title: 'Patagonia Snap-T Fleece Pullover — Teal M',
    description: 'Classic Synchilla Snap-T. Teal with brown snap. Very cosy.',
    price: 68,
    images: [IMGS.outerwear[0]],
    category: 'outerwear', subcategory: 'fleece',
    styles: ['outdoor', 'casual', 'gorpcore'], colors: ['teal', 'green'],
    size: 'M', brand: 'Patagonia', condition: 'good',
    priceRange: 1, likes: 201, views: 1220, sold: false,
  },
  {
    sellerId: 'seed_u25', sellerName: S['seed_u25'],
    title: 'Barbour Beaufort Wax Jacket — Olive M',
    description: 'Re-waxed this season. Classic tartan lining. Corduroy collar.',
    price: 145,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['outdoor', 'preppy', 'classic'], colors: ['olive', 'green'],
    size: 'M', brand: 'Barbour', condition: 'good',
    priceRange: 2, likes: 112, views: 680, sold: false,
  },
  {
    sellerId: 'seed_u44', sellerName: S['seed_u44'],
    title: 'The North Face Nuptse 700 Puffer — Black L',
    description: 'Down fill, iconic boxy silhouette. Worn one ski season.',
    price: 195,
    images: [IMGS.outerwear[4]],
    category: 'outerwear', subcategory: 'puffer',
    styles: ['outdoor', 'streetwear', 'gorpcore'], colors: ['black'],
    size: 'L', brand: 'The North Face', condition: 'good',
    priceRange: 3, likes: 388, views: 2360, sold: false,
  },
  {
    sellerId: 'seed_u44', sellerName: S['seed_u44'],
    title: 'Patagonia Nano Puff Vest — Black M',
    description: 'PrimaLoft fill, wind-resistant. Great layering piece.',
    price: 88,
    images: [IMGS.outerwear[5]],
    category: 'outerwear', subcategory: 'vest',
    styles: ['outdoor', 'minimal', 'gorpcore'], colors: ['black'],
    size: 'M', brand: 'Patagonia', condition: 'like_new',
    priceRange: 2, likes: 156, views: 940, sold: false,
  },
  {
    sellerId: 'seed_u19', sellerName: S['seed_u19'],
    title: 'Salomon Speedcross 5 — Black/Ebony 10.5',
    description: 'Aggressive trail lugs. One half-season of use. US 10.5.',
    price: 85,
    images: [IMGS.shoes[3]],
    category: 'shoes', subcategory: 'trail runners',
    styles: ['outdoor', 'gorpcore', 'techwear'], colors: ['black', 'grey'],
    size: '10.5', brand: 'Salomon', condition: 'good',
    priceRange: 2, likes: 215, views: 1300, sold: false,
  },
  {
    sellerId: 'seed_u19', sellerName: S['seed_u19'],
    title: 'Salomon XT-6 — Black/Phantom 10.5',
    description: 'The gorpcore icon. One season of light use.',
    price: 155,
    images: [IMGS.shoes[4]],
    category: 'shoes', subcategory: 'trail runners',
    styles: ['outdoor', 'techwear', 'gorpcore'], colors: ['black', 'grey'],
    size: '10.5', brand: 'Salomon', condition: 'good',
    priceRange: 2, likes: 384, views: 2200, sold: false,
  },
  {
    sellerId: 'seed_u05', sellerName: S['seed_u05'],
    title: 'Filson Original Tote — Tan/Brown OS',
    description: 'Rugged twill canvas, rolled top handles. Barely used.',
    price: 110,
    images: [IMGS.accessories[2]],
    category: 'accessories', subcategory: 'bags',
    styles: ['outdoor', 'preppy', 'workwear'], colors: ['tan', 'brown'],
    size: 'one size', brand: 'Filson', condition: 'good',
    priceRange: 2, likes: 143, views: 870, sold: false,
  },
  {
    sellerId: 'seed_u04', sellerName: S['seed_u04'],
    title: 'Snow Peak Wool Blend Shirt — Navy M',
    description: 'Wool-cotton blend. Excellent for camp or city. Size M.',
    price: 115,
    images: [IMGS.tops[2]],
    category: 'tops', subcategory: 'shirts',
    styles: ['outdoor', 'minimal', 'japanese'], colors: ['navy'],
    size: 'M', brand: 'Snow Peak', condition: 'like_new',
    priceRange: 2, likes: 162, views: 970, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PREPPY / CLASSIC (9 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u11', sellerName: S['seed_u11'],
    title: 'Polo Ralph Lauren Oxford BNWT — Blue M',
    description: 'Classic fit, light blue. Never worn — tags still on.',
    price: 35,
    images: [IMGS.tops[3]],
    category: 'tops', subcategory: 'shirts',
    styles: ['preppy', 'classic'], colors: ['blue', 'light blue'],
    size: 'M', brand: 'Ralph Lauren', condition: 'new',
    priceRange: 0, likes: 56, views: 340, sold: false,
  },
  {
    sellerId: 'seed_u36', sellerName: S['seed_u36'],
    title: 'Polo Ralph Lauren RLPC Vintage Wash Tee — Navy L',
    description: 'Garment-dyed, embroidered pony. The easy summer tee.',
    price: 28,
    images: [IMGS.tops[0]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['preppy', 'casual'], colors: ['navy'],
    size: 'L', brand: 'Ralph Lauren', condition: 'good',
    priceRange: 0, likes: 78, views: 490, sold: false,
  },
  {
    sellerId: 'seed_u11', sellerName: S['seed_u11'],
    title: 'Brooks Brothers Non-Iron OCBD — White 15-33',
    description: 'The classic American dress shirt. Non-iron twill. Nearly new.',
    price: 45,
    images: [IMGS.tops[2]],
    category: 'tops', subcategory: 'shirts',
    styles: ['preppy', 'classic', 'minimal'], colors: ['white'],
    size: '15-33', brand: 'Brooks Brothers', condition: 'like_new',
    priceRange: 0, likes: 62, views: 380, sold: false,
  },
  {
    sellerId: 'seed_u17', sellerName: S['seed_u17'],
    title: 'Polo Ralph Lauren Cable Knit Sweater — Cream L',
    description: 'Lambswool cable knit with polo pony. Cream, great condition.',
    price: 65,
    images: [IMGS.knitwear[0]],
    category: 'tops', subcategory: 'knitwear',
    styles: ['preppy', 'classic'], colors: ['cream', 'ivory'],
    size: 'L', brand: 'Ralph Lauren', condition: 'good',
    priceRange: 1, likes: 88, views: 530, sold: false,
  },
  {
    sellerId: 'seed_u40', sellerName: S['seed_u40'],
    title: 'Lacoste Classic L.12.12 Polo — White 5',
    description: 'The original piqué polo. Size 5 (EU). Clean and classic.',
    price: 52,
    images: [IMGS.tops[3]],
    category: 'tops', subcategory: 'polo',
    styles: ['preppy', 'minimal', 'classic'], colors: ['white'],
    size: '5', brand: 'Lacoste', condition: 'good',
    priceRange: 1, likes: 104, views: 630, sold: false,
  },
  {
    sellerId: 'seed_u40', sellerName: S['seed_u40'],
    title: 'Dockers Alpha Khaki Slim Chino — 32×30',
    description: 'The weekday chino. Khaki. Clean, no stains.',
    price: 28,
    images: [IMGS.bottoms[2]],
    category: 'bottoms', subcategory: 'chinos',
    styles: ['preppy', 'casual'], colors: ['khaki'],
    size: '32×30', brand: 'Dockers', condition: 'good',
    priceRange: 0, likes: 44, views: 280, sold: false,
  },
  {
    sellerId: 'seed_u26', sellerName: S['seed_u26'],
    title: 'Vintage Coach Saddle Bag — Tan',
    description: 'Full-grain leather Old Coach quality. Heavy brass hardware.',
    price: 165,
    images: [IMGS.accessories[4]],
    category: 'accessories', subcategory: 'bags',
    styles: ['preppy', 'vintage', 'classic'], colors: ['tan', 'brown'],
    size: 'one size', brand: 'Coach', condition: 'good',
    priceRange: 3, likes: 277, views: 1560, sold: false,
  },
  {
    sellerId: 'seed_u30', sellerName: S['seed_u30'],
    title: 'Seiko SKX013 Mod — Sapphire Crystal',
    description: 'NH35 movement, AR sapphire, brushed case. Keeps ±5 s/day.',
    price: 280,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'watches',
    styles: ['minimal', 'classic', 'preppy'], colors: ['black', 'silver'],
    size: 'one size', brand: 'Seiko', condition: 'like_new',
    priceRange: 3, likes: 193, views: 1140, sold: false,
  },
  {
    sellerId: 'seed_u32', sellerName: S['seed_u32'],
    title: 'New Era 59FIFTY Chicago Bulls 7⅜ — Black/Red',
    description: 'Classic colourway. No creasing. Sticker removed. Flat brim.',
    price: 35,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'hats',
    styles: ['streetwear', 'preppy', 'classic'], colors: ['black', 'red'],
    size: '7⅜', brand: 'New Era', condition: 'good',
    priceRange: 0, likes: 98, views: 560, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VINTAGE / ARCHIVE (12 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u01', sellerName: S['seed_u01'],
    title: "Vintage Levi's 501 — Medium Wash 32×30",
    description: "Classic straight-leg, great natural fade. '98 Levi's tab.",
    price: 65,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['vintage', 'americana', 'casual'], colors: ['blue', 'indigo'],
    size: '32×30', brand: "Levi's", condition: 'good',
    priceRange: 1, likes: 142, views: 890, sold: false,
  },
  {
    sellerId: 'seed_u12', sellerName: S['seed_u12'],
    title: "Vintage Harley-Davidson Single Stitch Tee — Black XL",
    description: "Huntington Beach '94. Single stitch. No cracks in the print.",
    price: 88,
    images: [IMGS.tops[4]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['vintage', 'americana', 'graphic'], colors: ['black'],
    size: 'XL', brand: 'Harley-Davidson', condition: 'good',
    priceRange: 1, likes: 201, views: 1100, sold: false,
  },
  {
    sellerId: 'seed_u13', sellerName: S['seed_u13'],
    title: 'Agolde 90s Pinch Waist Jeans — Dark Indigo 26',
    description: 'High rise, straight. Dark indigo. Size 26. Almost new.',
    price: 120,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['vintage', 'minimal', 'y2k'], colors: ['dark indigo', 'blue'],
    size: '26', brand: 'Agolde', condition: 'like_new',
    priceRange: 2, likes: 183, views: 1040, sold: false,
  },
  {
    sellerId: 'seed_u14', sellerName: S['seed_u14'],
    title: 'Vintage Champion Reverse Weave Sweatshirt — Grey S',
    description: 'Early 90s. Script logo, no cracks. Heavy reverse weave construction.',
    price: 110,
    images: [IMGS.tops[6]],
    category: 'tops', subcategory: 'sweatshirts',
    styles: ['vintage', 'americana', 'streetwear'], colors: ['grey'],
    size: 'S', brand: 'Champion', condition: 'good',
    priceRange: 2, likes: 267, views: 1580, sold: false,
  },
  {
    sellerId: 'seed_u33', sellerName: S['seed_u33'],
    title: 'Needles Rebuild Flannel Overshirt — Multi M/L',
    description: 'Patchwork flannel rebuild. One-of-a-kind Needles workmanship.',
    price: 195,
    images: [IMGS.tops[3]],
    category: 'tops', subcategory: 'shirts',
    styles: ['vintage', 'japanese', 'avant garde'], colors: ['multicolor', 'plaid'],
    size: 'M/L', brand: 'Needles', condition: 'good',
    priceRange: 3, likes: 344, views: 2100, sold: false,
  },
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Vintage Grateful Dead Tie-Dye Tee — Tour 94 XL',
    description: "Summer '94 tour. Single stitch, hand tie-dye. Tiny hole inside collar.",
    price: 145,
    images: [IMGS.hoodies[1]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['vintage', 'americana', 'graphic'], colors: ['multicolor', 'tie-dye'],
    size: 'XL', brand: 'Vintage', condition: 'good',
    priceRange: 2, likes: 312, views: 1900, sold: false,
  },
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Wrangler Cowboy Cut Western Shirt — Pearl Snap M',
    description: "Pearl snap buttons, classic western yoke. Great '70s vibes.",
    price: 42,
    images: [IMGS.tops[3]],
    category: 'tops', subcategory: 'shirts',
    styles: ['vintage', 'americana', 'western'], colors: ['brown', 'plaid'],
    size: 'M', brand: 'Wrangler', condition: 'good',
    priceRange: 0, likes: 88, views: 540, sold: false,
  },
  {
    sellerId: 'seed_u12', sellerName: S['seed_u12'],
    title: '90s Tommy Hilfiger Windbreaker — Red/White/Blue L',
    description: 'Classic tricolour flag logo on chest. All original hardware.',
    price: 95,
    images: [IMGS.outerwear[0]],
    category: 'outerwear', subcategory: 'windbreaker',
    styles: ['vintage', 'y2k', 'americana'], colors: ['red', 'white', 'blue'],
    size: 'L', brand: 'Tommy Hilfiger', condition: 'good',
    priceRange: 2, likes: 244, views: 1460, sold: false,
  },
  {
    sellerId: 'seed_u13', sellerName: S['seed_u13'],
    title: "Levi's 550 Relaxed Fit — Dark Stonewash 34×30",
    description: "Late 90s 550. Great stonewash, perfect relaxed taper. No flaws.",
    price: 45,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['vintage', 'americana', 'casual'], colors: ['blue', 'dark wash'],
    size: '34×30', brand: "Levi's", condition: 'good',
    priceRange: 0, likes: 107, views: 650, sold: false,
  },
  {
    sellerId: 'seed_u09', sellerName: S['seed_u09'],
    title: 'Vintage Military M-65 Field Jacket — Olive M',
    description: 'Genuine US military issue. Brass zip, storm flap. Classic.',
    price: 95,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['vintage', 'military', 'utility', 'outdoor'], colors: ['olive', 'green'],
    size: 'M', brand: 'Alpha Industries', condition: 'good',
    priceRange: 2, likes: 198, views: 1200, sold: false,
  },
  {
    sellerId: 'seed_u09', sellerName: S['seed_u09'],
    title: 'Vintage Leather Moto Jacket — Black M',
    description: 'Real cowhide leather, asymmetric zip. Buttery soft with age.',
    price: 220,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['vintage', 'moto', 'edgy'], colors: ['black'],
    size: 'M', brand: 'Unknown', condition: 'good',
    priceRange: 3, likes: 412, views: 2340, sold: false,
  },
  {
    sellerId: 'seed_u42', sellerName: S['seed_u42'],
    title: 'Vintage Denim Jacket — Dark Wash M',
    description: 'Washed to perfection. Orange stitching, brass buttons. Unbranded.',
    price: 55,
    images: [IMGS.denim[0]],
    category: 'outerwear', subcategory: 'denim jacket',
    styles: ['vintage', 'casual', 'americana'], colors: ['blue', 'dark wash'],
    size: 'M', brand: 'Unknown', condition: 'good',
    priceRange: 1, likes: 134, views: 810, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SNEAKERS (additional dedicated section)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u02', sellerName: S['seed_u02'],
    title: 'New Balance 990v3 — Grey USA 11',
    description: 'Made in USA. Light crease on toe box. Size 11.',
    price: 175,
    images: [IMGS.shoes[0]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['minimal', 'casual', 'gorpcore'], colors: ['grey'],
    size: '11', brand: 'New Balance', condition: 'good',
    priceRange: 3, likes: 167, views: 990, sold: false,
  },
  {
    sellerId: 'seed_u18', sellerName: S['seed_u18'],
    title: 'Adidas Samba OG — White/Gum 9.5 (DS)',
    description: 'Deadstock, never worn. Size 9.5. The shoe of the moment.',
    price: 130,
    images: [IMGS.shoes[1]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['minimal', 'classic', 'casual'], colors: ['white', 'gum'],
    size: '9.5', brand: 'Adidas', condition: 'new',
    priceRange: 2, likes: 512, views: 3300, sold: false,
  },
  {
    sellerId: 'seed_u04', sellerName: S['seed_u04'],
    title: 'Nike Air Force 1 Low — White 10',
    description: 'Lightly worn, soles clean. Comes with extra laces.',
    price: 85,
    images: [IMGS.shoes[4]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['streetwear', 'minimal', 'casual'], colors: ['white'],
    size: '10', brand: 'Nike', condition: 'like_new',
    priceRange: 2, likes: 213, views: 1250, sold: false,
  },
  {
    sellerId: 'seed_u20', sellerName: S['seed_u20'],
    title: 'Air Jordan 1 Retro High OG Chicago — 10 (2022)',
    description: 'DS. Size 10. 2022 release, box has minor shelf wear.',
    price: 380,
    images: [IMGS.shoes[2]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['streetwear', 'hypebeast', 'classic'], colors: ['red', 'white', 'black'],
    size: '10', brand: 'Jordan', condition: 'new',
    priceRange: 3, likes: 720, views: 4800, sold: false,
  },
  {
    sellerId: 'seed_u21', sellerName: S['seed_u21'],
    title: 'Asics Gel-Kayano 14 — Cream/Sage Green 9',
    description: 'The Pinterest sneaker. Size 9. One season worn.',
    price: 140,
    images: [IMGS.shoes[0]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['y2k', 'minimal', 'gorpcore'], colors: ['cream', 'sage'],
    size: '9', brand: 'Asics', condition: 'like_new',
    priceRange: 2, likes: 445, views: 2780, sold: false,
  },
  {
    sellerId: 'seed_u41', sellerName: S['seed_u41'],
    title: 'Birkenstock Arizona Suede — Taupe EU 43',
    description: 'Broken in perfectly. Suede upper, cork footbed shaped to the foot.',
    price: 75,
    images: [IMGS.shoes[3]],
    category: 'shoes', subcategory: 'sandals',
    styles: ['minimal', 'casual', 'bohemian'], colors: ['taupe', 'brown'],
    size: 'EU 43', brand: 'Birkenstock', condition: 'good',
    priceRange: 1, likes: 167, views: 990, sold: false,
  },
  {
    sellerId: 'seed_u42', sellerName: S['seed_u42'],
    title: 'Vans Old Skool — Black/White 10',
    description: 'The OG. Side stripe intact. Barely worn. Size 10.',
    price: 45,
    images: [IMGS.shoes[0]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['skate', 'casual', 'streetwear'], colors: ['black', 'white'],
    size: '10', brand: 'Vans', condition: 'like_new',
    priceRange: 0, likes: 98, views: 580, sold: false,
  },
  {
    sellerId: 'seed_u43', sellerName: S['seed_u43'],
    title: 'Dr. Martens 1460 Cherry Red — 8-Eye UK 6',
    description: 'Good Goodyear welt. Cherry red. Size UK 6.',
    price: 120,
    images: [IMGS.shoes[2]],
    category: 'shoes', subcategory: 'boots',
    styles: ['vintage', 'edgy', 'classic'], colors: ['red', 'cherry'],
    size: 'UK 6', brand: 'Dr. Martens', condition: 'good',
    priceRange: 2, likes: 189, views: 1120, sold: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WOMEN'S FASHION (10 items)
  // ══════════════════════════════════════════════════════════════════════════
  {
    sellerId: 'seed_u26', sellerName: S['seed_u26'],
    title: 'Floral Maxi Dress — Pink/Multi M',
    description: 'Flowy, elastic waist, V-neck. Perfect beach-to-bar.',
    price: 48,
    images: [IMGS.dresses[1]],
    category: 'dresses', subcategory: 'maxi dress',
    styles: ['bohemian', 'floral', 'casual'], colors: ['pink', 'multicolor'],
    size: 'M', brand: 'Free People', condition: 'good',
    priceRange: 0, likes: 128, views: 780, sold: false,
  },
  {
    sellerId: 'seed_u27', sellerName: S['seed_u27'],
    title: 'Reformation Linen Mini Dress — Butter Yellow 2',
    description: '100% linen, smocked back, adjustable straps. Size 2.',
    price: 95,
    images: [IMGS.dresses[3]],
    category: 'dresses', subcategory: 'mini dress',
    styles: ['minimal', 'casual', 'elegant'], colors: ['yellow'],
    size: '2', brand: 'Reformation', condition: 'like_new',
    priceRange: 2, likes: 278, views: 1540, sold: false,
  },
  {
    sellerId: 'seed_u28', sellerName: S['seed_u28'],
    title: 'Caro Editions Smocked Sundress — Ivory M',
    description: 'Hand-smocked cotton, ethical production. Ivory.',
    price: 125,
    images: [IMGS.dresses[0]],
    category: 'dresses', subcategory: 'sundress',
    styles: ['bohemian', 'artisanal', 'elegant'], colors: ['white', 'ivory'],
    size: 'M', brand: 'Caro Editions', condition: 'new',
    priceRange: 2, likes: 189, views: 1020, sold: false,
  },
  {
    sellerId: 'seed_u49', sellerName: S['seed_u49'],
    title: 'Farm Rio Print Midi Skirt — Tropical M',
    description: 'Bold tropical print, elasticated waist, midi length.',
    price: 65,
    images: [IMGS.dresses[4]],
    category: 'bottoms', subcategory: 'skirts',
    styles: ['bohemian', 'tropical', 'floral'], colors: ['multicolor', 'green'],
    size: 'M', brand: 'Farm Rio', condition: 'like_new',
    priceRange: 1, likes: 210, views: 1280, sold: false,
  },
  {
    sellerId: 'seed_u29', sellerName: S['seed_u29'],
    title: 'Gold Layering Necklace Set — 18k Plated',
    description: '18k gold-plated. Three lengths — choker, mid, long. No tarnish.',
    price: 42,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'jewelry',
    styles: ['minimal', 'elegant', 'bohemian'], colors: ['gold'],
    size: 'one size', brand: 'Mejuri', condition: 'new',
    priceRange: 0, likes: 389, views: 2100, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: 'Aritzia Wilfred Free Wrap Dress — Sage Green S',
    description: 'Crepe fabric, wrap style, self-tie belt. Sage green, worn once.',
    price: 58,
    images: [IMGS.dresses[3]],
    category: 'dresses', subcategory: 'wrap dress',
    styles: ['minimal', 'casual', 'elegant'], colors: ['sage', 'green'],
    size: 'S', brand: 'Aritzia', condition: 'like_new',
    priceRange: 1, likes: 174, views: 1050, sold: false,
  },
  {
    sellerId: 'seed_u31', sellerName: S['seed_u31'],
    title: 'By Far Rachel Bag — Powder Pink Croc',
    description: 'Croc-embossed leather, chain strap, top handle. Barely used.',
    price: 290,
    images: [IMGS.accessories[4]],
    category: 'accessories', subcategory: 'bags',
    styles: ['luxury', 'minimal', 'y2k'], colors: ['pink', 'blush'],
    size: 'one size', brand: 'By Far', condition: 'like_new',
    priceRange: 3, likes: 345, views: 2080, sold: false,
  },
  {
    sellerId: 'seed_u49', sellerName: S['seed_u49'],
    title: 'Free People Movement Wrap Cardigan — Cream OS',
    description: 'Super-soft knit, oversized, great for layering. One size.',
    price: 55,
    images: [IMGS.knitwear[1]],
    category: 'tops', subcategory: 'knitwear',
    styles: ['bohemian', 'casual', 'minimal'], colors: ['cream', 'ivory'],
    size: 'one size', brand: 'Free People', condition: 'like_new',
    priceRange: 1, likes: 166, views: 1000, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: 'Toteme Straight-Leg Jeans — Dark Blue 38',
    description: 'High-waist, dark indigo, straight leg. Pristine condition.',
    price: 175,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['minimal', 'luxury'], colors: ['dark blue', 'indigo'],
    size: '38', brand: 'Toteme', condition: 'like_new',
    priceRange: 3, likes: 242, views: 1460, sold: false,
  },
  {
    sellerId: 'seed_u50', sellerName: S['seed_u50'],
    title: 'COS Wide-Leg Linen Trousers — Natural White S',
    description: 'Pure linen, wide-leg silhouette. Natural white, drawstring waist.',
    price: 52,
    images: [IMGS.bottoms[2]],
    category: 'bottoms', subcategory: 'trousers',
    styles: ['minimal', 'casual'], colors: ['white', 'natural'],
    size: 'S', brand: 'COS', condition: 'like_new',
    priceRange: 1, likes: 123, views: 750, sold: false,
  },
  // ══════════════════════════════════════════════════════════════════════════
  // BATCH 2 — 50 new items (streetwear, luxury, vintage, women's, sneakers)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Streetwear / Hype ─────────────────────────────────────────────────────
  {
    sellerId: 'seed_u01', sellerName: S['seed_u01'],
    title: 'Fear of God Essentials Hoodie — Taupe M',
    description: 'FW22. Chest logo, dropped shoulders. Barely worn — smells like fabric softener. Taupe.',
    price: 88,
    images: [IMGS.hoodies[0]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['streetwear', 'minimal'], colors: ['taupe', 'beige'],
    size: 'M', brand: 'Fear of God Essentials', condition: 'like_new',
    priceRange: 2, likes: 541, views: 3400, sold: false,
  },
  {
    sellerId: 'seed_u06', sellerName: S['seed_u06'],
    title: 'Gallery Dept. Paint-Splatter Flare Pant — Black M',
    description: 'Hand-distressed paint details, flared hem. Worn once. Very editorial.',
    price: 295,
    images: [IMGS.bottoms[4]],
    category: 'bottoms', subcategory: 'pants',
    styles: ['streetwear', 'vintage', 'avant garde'], colors: ['black', 'multicolor'],
    size: 'M', brand: 'Gallery Dept.', condition: 'like_new',
    priceRange: 3, likes: 612, views: 3900, sold: false,
  },
  {
    sellerId: 'seed_u24', sellerName: S['seed_u24'],
    title: 'Aime Leon Dore Coaches Jacket — Olive L',
    description: 'ALD script embroidery, snap buttons, nylon shell. One of the best coaches around.',
    price: 215,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['streetwear', 'preppy'], colors: ['olive', 'green'],
    size: 'L', brand: 'Aime Leon Dore', condition: 'like_new',
    priceRange: 3, likes: 488, views: 3100, sold: false,
  },
  {
    sellerId: 'seed_u03', sellerName: S['seed_u03'],
    title: 'Carhartt WIP Chase Hoodie — Black/Gold M',
    description: 'Heavyweight 315-gsm fleece, embroidered chest C logo. Clean condition.',
    price: 72,
    images: [IMGS.hoodies[2]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['streetwear', 'workwear'], colors: ['black', 'gold'],
    size: 'M', brand: 'Carhartt WIP', condition: 'like_new',
    priceRange: 1, likes: 203, views: 1240, sold: false,
  },
  {
    sellerId: 'seed_u04', sellerName: S['seed_u04'],
    title: 'Engineered Garments Bedform Shirt — Olive Houndstooth M',
    description: 'Classic EG Bedform camp-collar shirt. Houndstooth wool-blend, chest pockets.',
    price: 145,
    images: [IMGS.tops[2]],
    category: 'tops', subcategory: 'shirts',
    styles: ['outdoor', 'vintage', 'workwear'], colors: ['olive'],
    size: 'M', brand: 'Engineered Garments', condition: 'like_new',
    priceRange: 2, likes: 189, views: 1110, sold: false,
  },
  {
    sellerId: 'seed_u33', sellerName: S['seed_u33'],
    title: 'Dickies 874 Work Pant — Black 32×30',
    description: 'The original workwear pant. Relaxed fit, clean unwashed black. Deadstock.',
    price: 32,
    images: [IMGS.bottoms[4]],
    category: 'bottoms', subcategory: 'pants',
    styles: ['workwear', 'streetwear', 'vintage'], colors: ['black'],
    size: '32×30', brand: 'Dickies', condition: 'new',
    priceRange: 0, likes: 126, views: 760, sold: false,
  },
  {
    sellerId: 'seed_u05', sellerName: S['seed_u05'],
    title: 'Neighborhood Savage Crewneck — Black L',
    description: 'Chain-stitch embroidery, ribbed hem and cuffs. Clean — no pilling.',
    price: 195,
    images: [IMGS.tops[5]],
    category: 'tops', subcategory: 'crewneck',
    styles: ['streetwear', 'japanese', 'moto'], colors: ['black'],
    size: 'L', brand: 'Neighborhood', condition: 'good',
    priceRange: 3, likes: 277, views: 1680, sold: false,
  },
  {
    sellerId: 'seed_u06', sellerName: S['seed_u06'],
    title: 'Stüssy SS-Link Fleece Jacket — Bone M',
    description: 'SS-Link logo embroidery. Sherpa-feel fleece. Bone/off-white.',
    price: 135,
    images: [IMGS.outerwear[5]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['streetwear', 'casual'], colors: ['bone', 'cream'],
    size: 'M', brand: 'Stüssy', condition: 'like_new',
    priceRange: 2, likes: 344, views: 2100, sold: false,
  },
  {
    sellerId: 'seed_u01', sellerName: S['seed_u01'],
    title: 'A-Cold-Wall* Panelled Overshirt — Slate Grey M',
    description: 'Nylon/ripstop panels, asymmetric zip. Signature ACW* utility aesthetic.',
    price: 260,
    images: [IMGS.outerwear[0]],
    category: 'tops', subcategory: 'shirts',
    styles: ['techwear', 'minimal', 'streetwear'], colors: ['grey', 'slate'],
    size: 'M', brand: 'A-Cold-Wall*', condition: 'like_new',
    priceRange: 3, likes: 298, views: 1840, sold: false,
  },
  {
    sellerId: 'seed_u32', sellerName: S['seed_u32'],
    title: 'Noah NYC Core Logo Tee — Navy L',
    description: 'Noah serif logo chest print. 100% pima cotton. Two wears.',
    price: 55,
    images: [IMGS.tops[0]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['preppy', 'streetwear'], colors: ['navy'],
    size: 'L', brand: 'Noah NYC', condition: 'like_new',
    priceRange: 1, likes: 134, views: 820, sold: false,
  },

  // ── Luxury / Designer ─────────────────────────────────────────────────────
  {
    sellerId: 'seed_u47', sellerName: S['seed_u47'],
    title: 'Post Archive Faction 5.0 Center Jacket — Black L',
    description: 'Technical shell, seam-sealed, modular zip system. PAF SS23.',
    price: 680,
    images: [IMGS.outerwear[3]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['techwear', 'luxury', 'minimal'], colors: ['black'],
    size: 'L', brand: 'Post Archive Faction', condition: 'like_new',
    priceRange: 4, likes: 421, views: 2680, sold: false,
  },
  {
    sellerId: 'seed_u10', sellerName: S['seed_u10'],
    title: 'Our Legacy Borrowed Chino — Mud Brown 30',
    description: 'Relaxed wide-leg chino. Mud brown, mid-rise. Our Legacy deadstock.',
    price: 165,
    images: [IMGS.bottoms[1]],
    category: 'bottoms', subcategory: 'chinos',
    styles: ['minimal', 'luxury'], colors: ['brown', 'mud'],
    size: '30', brand: 'Our Legacy', condition: 'good',
    priceRange: 2, likes: 244, views: 1490, sold: false,
  },
  {
    sellerId: 'seed_u37', sellerName: S['seed_u37'],
    title: 'Maison Kitsuné Fox Patch Hoodie — Khaki M',
    description: 'Classic fox appliqué on chest. Midweight French terry. Barely worn.',
    price: 118,
    images: [IMGS.hoodies[0]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['luxury', 'minimal', 'preppy'], colors: ['khaki', 'tan'],
    size: 'M', brand: 'Maison Kitsuné', condition: 'like_new',
    priceRange: 2, likes: 311, views: 1900, sold: false,
  },
  {
    sellerId: 'seed_u15', sellerName: S['seed_u15'],
    title: 'Ami Paris ADC Heart Logo Crewneck — Heather Grey L',
    description: 'Embroidered ADC heart. 80% cotton 20% polyester French terry. Clean.',
    price: 145,
    images: [IMGS.tops[6]],
    category: 'tops', subcategory: 'crewneck',
    styles: ['luxury', 'minimal'], colors: ['grey', 'heather'],
    size: 'L', brand: 'Ami Paris', condition: 'like_new',
    priceRange: 2, likes: 267, views: 1620, sold: false,
  },
  {
    sellerId: 'seed_u39', sellerName: S['seed_u39'],
    title: 'Jil Sander Collarless Blazer — Camel 48',
    description: 'Single-button collarless construction. Pure wool. Dry-cleaned. EU 48.',
    price: 420,
    images: [IMGS.outerwear[2]],
    category: 'outerwear', subcategory: 'blazer',
    styles: ['luxury', 'minimal'], colors: ['camel', 'tan'],
    size: '48', brand: 'Jil Sander', condition: 'good',
    priceRange: 4, likes: 189, views: 1130, sold: false,
  },
  {
    sellerId: 'seed_u47', sellerName: S['seed_u47'],
    title: 'Craig Green Worker Jacket — Khaki S',
    description: 'Cotton canvas, eyelet detailing, deconstructed seams. Craig Green FW21.',
    price: 490,
    images: [IMGS.outerwear[1]],
    category: 'outerwear', subcategory: 'jacket',
    styles: ['luxury', 'avant garde', 'minimal'], colors: ['khaki'],
    size: 'S', brand: 'Craig Green', condition: 'like_new',
    priceRange: 4, likes: 214, views: 1340, sold: false,
  },
  {
    sellerId: 'seed_u16', sellerName: S['seed_u16'],
    title: 'Needles Track Pant — Orange M',
    description: 'Butterfly embroidery down the seam. Tricot fabric, snaps all the way up.',
    price: 185,
    images: [IMGS.bottoms[3]],
    category: 'bottoms', subcategory: 'track pants',
    styles: ['vintage', 'streetwear', 'japanese'], colors: ['orange'],
    size: 'M', brand: 'Needles', condition: 'like_new',
    priceRange: 3, likes: 534, views: 3400, sold: false,
  },
  {
    sellerId: 'seed_u10', sellerName: S['seed_u10'],
    title: 'Lemaire Chino — Sand 44',
    description: 'Single pleat, straight leg, cotton twill. Sand beige. EU 44.',
    price: 240,
    images: [IMGS.bottoms[2]],
    category: 'bottoms', subcategory: 'chinos',
    styles: ['minimal', 'luxury'], colors: ['sand', 'beige'],
    size: '44', brand: 'Lemaire', condition: 'like_new',
    priceRange: 3, likes: 178, views: 1050, sold: false,
  },
  {
    sellerId: 'seed_u31', sellerName: S['seed_u31'],
    title: 'Celine Triomphe Card Holder — Tan Calfskin',
    description: 'Triomphe logo hardware. Calfskin leather. Near-perfect condition.',
    price: 380,
    images: [IMGS.accessories[1]],
    category: 'accessories', subcategory: 'wallet',
    styles: ['luxury', 'minimal'], colors: ['tan', 'brown'],
    size: 'one size', brand: 'Celine', condition: 'like_new',
    priceRange: 4, likes: 445, views: 2790, sold: false,
  },
  {
    sellerId: 'seed_u45', sellerName: S['seed_u45'],
    title: 'Marni Striped Logo Tee — Blue/Ivory M',
    description: 'Boxy fit, heavyweight jersey, Marni text block print. SS23.',
    price: 140,
    images: [IMGS.tops[1]],
    category: 'tops', subcategory: 't-shirts',
    styles: ['luxury', 'minimal', 'streetwear'], colors: ['blue', 'ivory', 'stripe'],
    size: 'M', brand: 'Marni', condition: 'like_new',
    priceRange: 2, likes: 301, views: 1880, sold: false,
  },

  // ── Vintage / Archive ─────────────────────────────────────────────────────
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Vintage Adidas Franz Beckenbauer Track Jacket — Black L',
    description: "Trefoil badge, ribbed cuffs, 3-stripe arms. Mid-90s. Great condition.",
    price: 145,
    images: [IMGS.outerwear[0]],
    category: 'outerwear', subcategory: 'track jacket',
    styles: ['vintage', 'streetwear', 'americana'], colors: ['black'],
    size: 'L', brand: 'Adidas', condition: 'good',
    priceRange: 2, likes: 312, views: 1890, sold: false,
  },
  {
    sellerId: 'seed_u12', sellerName: S['seed_u12'],
    title: 'Y2K Von Dutch Trucker Hat — Red/White OS',
    description: "Classic Von Dutch logo patch. Red mesh, snapback. Perfect Y2K artifact.",
    price: 38,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'hats',
    styles: ['vintage', 'y2k', 'streetwear'], colors: ['red', 'white'],
    size: 'one size', brand: 'Von Dutch', condition: 'good',
    priceRange: 0, likes: 287, views: 1740, sold: false,
  },
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Vintage Polo Sport Windbreaker — Navy/Red M',
    description: "Classic woven Polo Sport logo. Packable shell, zip-off hood. '97.",
    price: 110,
    images: [IMGS.outerwear[3]],
    category: 'outerwear', subcategory: 'windbreaker',
    styles: ['vintage', 'y2k', 'streetwear'], colors: ['navy', 'red'],
    size: 'M', brand: 'Ralph Lauren', condition: 'good',
    priceRange: 2, likes: 234, views: 1420, sold: false,
  },
  {
    sellerId: 'seed_u14', sellerName: S['seed_u14'],
    title: 'Vintage Champion Hoodie — Oxford Grey XL',
    description: 'Super-heavyweight reverse weave. C logo patch. No cracks, no fade.',
    price: 95,
    images: [IMGS.hoodies[2]],
    category: 'tops', subcategory: 'hoodies',
    styles: ['vintage', 'americana', 'streetwear'], colors: ['grey'],
    size: 'XL', brand: 'Champion', condition: 'good',
    priceRange: 2, likes: 198, views: 1190, sold: false,
  },
  {
    sellerId: 'seed_u12', sellerName: S['seed_u12'],
    title: '90s Tommy Hilfiger Crest Logo Crew — Red/Navy M',
    description: 'Embroidered chest crest. All cotton. Genuine 90s garment.',
    price: 78,
    images: [IMGS.tops[6]],
    category: 'tops', subcategory: 'crewneck',
    styles: ['vintage', 'y2k', 'preppy'], colors: ['red', 'navy'],
    size: 'M', brand: 'Tommy Hilfiger', condition: 'good',
    priceRange: 1, likes: 222, views: 1340, sold: false,
  },
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Vintage Reebok Classic Track Pant — Black/White M',
    description: "Straight leg, piping down the sides, Reebok vector logo. 90s.",
    price: 55,
    images: [IMGS.bottoms[4]],
    category: 'bottoms', subcategory: 'track pants',
    styles: ['vintage', 'americana', 'streetwear'], colors: ['black', 'white'],
    size: 'M', brand: 'Reebok', condition: 'good',
    priceRange: 1, likes: 161, views: 970, sold: false,
  },
  {
    sellerId: 'seed_u14', sellerName: S['seed_u14'],
    title: 'Vintage Nautica Sailing Logo Fleece — Navy L',
    description: 'Embroidered Nautica sailing logo, full zip. Classic early-90s piece.',
    price: 88,
    images: [IMGS.outerwear[5]],
    category: 'outerwear', subcategory: 'fleece',
    styles: ['vintage', 'preppy', 'y2k'], colors: ['navy'],
    size: 'L', brand: 'Nautica', condition: 'good',
    priceRange: 1, likes: 177, views: 1070, sold: false,
  },
  {
    sellerId: 'seed_u12', sellerName: S['seed_u12'],
    title: 'Vintage Fila BJ Logo Track Jacket — White/Navy M',
    description: 'BJ logo embroidered chest, contrast piping. Very clean for its age.',
    price: 92,
    images: [IMGS.outerwear[0]],
    category: 'outerwear', subcategory: 'track jacket',
    styles: ['vintage', 'streetwear'], colors: ['white', 'navy'],
    size: 'M', brand: 'Fila', condition: 'good',
    priceRange: 1, likes: 143, views: 870, sold: false,
  },
  {
    sellerId: 'seed_u48', sellerName: S['seed_u48'],
    title: 'Vintage Lee Dungaree Jeans — Stonewash 32×30',
    description: "Great mid-wash stonewash. Relaxed '92 fit. Tag reads 32×30.",
    price: 52,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['vintage', 'americana'], colors: ['blue', 'stonewash'],
    size: '32×30', brand: 'Lee', condition: 'good',
    priceRange: 1, likes: 98, views: 590, sold: false,
  },
  {
    sellerId: 'seed_u09', sellerName: S['seed_u09'],
    title: "Vintage Levi's Sherpa Trucker Jacket — Dark Wash M",
    description: "Double-sided sherpa lining, classic Levi's denim shell. Very cosy.",
    price: 115,
    images: [IMGS.denim[2]],
    category: 'outerwear', subcategory: 'denim jacket',
    styles: ['vintage', 'americana', 'casual'], colors: ['blue', 'dark wash', 'cream'],
    size: 'M', brand: "Levi's", condition: 'good',
    priceRange: 2, likes: 211, views: 1280, sold: false,
  },
  {
    sellerId: 'seed_u42', sellerName: S['seed_u42'],
    title: 'Vintage Starter Chicago Bulls Pullover — Black M',
    description: 'Satin finish, embroidered wordmark. 90s deadstock from a Chicago estate sale.',
    price: 135,
    images: [IMGS.tops[4]],
    category: 'tops', subcategory: 'pullover',
    styles: ['vintage', 'streetwear', 'americana'], colors: ['black', 'red'],
    size: 'M', brand: 'Starter', condition: 'like_new',
    priceRange: 2, likes: 366, views: 2240, sold: false,
  },

  // ── Women's Fashion ───────────────────────────────────────────────────────
  {
    sellerId: 'seed_u27', sellerName: S['seed_u27'],
    title: 'Madewell Perfect Vintage Straight Jean — Light Wash 27',
    description: 'High-rise, straight leg, light wash. Worn twice — still stiff.',
    price: 68,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['minimal', 'casual'], colors: ['light blue', 'wash'],
    size: '27', brand: 'Madewell', condition: 'like_new',
    priceRange: 1, likes: 178, views: 1060, sold: false,
  },
  {
    sellerId: 'seed_u27', sellerName: S['seed_u27'],
    title: 'Abercrombie 90s Straight Jeans — Dark Wash 27',
    description: 'High-rise, 90s straight silhouette. Dark wash with slight whiskering.',
    price: 55,
    images: [IMGS.bottoms[0]],
    category: 'bottoms', subcategory: 'jeans',
    styles: ['vintage', 'casual'], colors: ['dark blue', 'dark wash'],
    size: '27', brand: 'Abercrombie & Fitch', condition: 'like_new',
    priceRange: 1, likes: 201, views: 1230, sold: false,
  },
  {
    sellerId: 'seed_u50', sellerName: S['seed_u50'],
    title: 'Sézane Augustin Cardigan — Camel M',
    description: 'Chunky rib-knit, oversized, button front. Camel — goes with everything.',
    price: 88,
    images: [IMGS.knitwear[0]],
    category: 'tops', subcategory: 'knitwear',
    styles: ['minimal', 'preppy'], colors: ['camel', 'tan'],
    size: 'M', brand: 'Sézane', condition: 'like_new',
    priceRange: 2, likes: 345, views: 2100, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: '& Other Stories Button-Down Maxi Dress — White S',
    description: 'Crisp white, tiered hem, button-front. One wear, dry-cleaned.',
    price: 62,
    images: [IMGS.dresses[2]],
    category: 'dresses', subcategory: 'maxi dress',
    styles: ['minimal', 'casual', 'elegant'], colors: ['white'],
    size: 'S', brand: '& Other Stories', condition: 'like_new',
    priceRange: 1, likes: 212, views: 1290, sold: false,
  },
  {
    sellerId: 'seed_u28', sellerName: S['seed_u28'],
    title: 'Zimmermann Floral Midi Dress — Multi 0',
    description: 'Silk-blend, flutter sleeve, ruched bodice. Size 0. Wore to two events.',
    price: 380,
    images: [IMGS.dresses[1]],
    category: 'dresses', subcategory: 'midi dress',
    styles: ['luxury', 'elegant', 'bohemian'], colors: ['multicolor', 'floral'],
    size: '0', brand: 'Zimmermann', condition: 'good',
    priceRange: 4, likes: 467, views: 2890, sold: false,
  },
  {
    sellerId: 'seed_u27', sellerName: S['seed_u27'],
    title: 'Faithfull The Brand Sundress — Terracotta S',
    description: 'Smocked bodice, adjustable straps, flowy midi length. One wear.',
    price: 98,
    images: [IMGS.dresses[4]],
    category: 'dresses', subcategory: 'sundress',
    styles: ['bohemian', 'casual', 'floral'], colors: ['terracotta', 'rust'],
    size: 'S', brand: 'Faithfull The Brand', condition: 'like_new',
    priceRange: 2, likes: 289, views: 1760, sold: false,
  },
  {
    sellerId: 'seed_u50', sellerName: S['seed_u50'],
    title: 'Zara Satin Slip Skirt — Camel XS',
    description: 'Bias cut, elastic waist, midi length. Camel satin. Two wears.',
    price: 32,
    images: [IMGS.dresses[3]],
    category: 'bottoms', subcategory: 'skirts',
    styles: ['minimal', 'elegant', 'y2k'], colors: ['camel', 'tan'],
    size: 'XS', brand: 'Zara', condition: 'like_new',
    priceRange: 0, likes: 198, views: 1190, sold: false,
  },
  {
    sellerId: 'seed_u29', sellerName: S['seed_u29'],
    title: 'Pandora Moments Heart Clasp Bracelet — Rose Gold',
    description: 'Sterling silver with rose gold plating. Heart clasp, like new.',
    price: 38,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'jewelry',
    styles: ['minimal', 'elegant'], colors: ['rose gold', 'pink'],
    size: 'one size', brand: 'Pandora', condition: 'like_new',
    priceRange: 0, likes: 267, views: 1600, sold: false,
  },
  {
    sellerId: 'seed_u31', sellerName: S['seed_u31'],
    title: 'By Far Mini Rachel Bag — Caramel Croc-Embossed',
    description: 'Croc-embossed leather, top handle + chain strap. Barely used. Dustbag included.',
    price: 265,
    images: [IMGS.accessories[4]],
    category: 'accessories', subcategory: 'bags',
    styles: ['luxury', 'minimal', 'y2k'], colors: ['caramel', 'brown'],
    size: 'one size', brand: 'By Far', condition: 'like_new',
    priceRange: 3, likes: 412, views: 2580, sold: false,
  },
  {
    sellerId: 'seed_u46', sellerName: S['seed_u46'],
    title: 'Mango Linen Blazer — Cream 6',
    description: 'Relaxed single-button, patch pockets. Cream linen. Worn once to a meeting.',
    price: 42,
    images: [IMGS.outerwear[2]],
    category: 'outerwear', subcategory: 'blazer',
    styles: ['minimal', 'casual', 'preppy'], colors: ['cream', 'ivory'],
    size: '6', brand: 'Mango', condition: 'like_new',
    priceRange: 0, likes: 134, views: 810, sold: false,
  },

  // ── Sneakers ──────────────────────────────────────────────────────────────
  {
    sellerId: 'seed_u18', sellerName: S['seed_u18'],
    title: 'Adidas Campus 00s — White/Core Black 9.5',
    description: 'The successor to the Samba. Deadstock pair, never worn. Size 9.5.',
    price: 110,
    images: [IMGS.shoes[1]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['streetwear', 'casual', 'vintage'], colors: ['white', 'black'],
    size: '9.5', brand: 'Adidas', condition: 'new',
    priceRange: 2, likes: 489, views: 3100, sold: false,
  },
  {
    sellerId: 'seed_u04', sellerName: S['seed_u04'],
    title: 'Nike Air Max 90 — Triple Black 10.5',
    description: 'All-black upper, midsole, sole. Worn twice — perfect condition.',
    price: 105,
    images: [IMGS.shoes[3]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['streetwear', 'minimal'], colors: ['black'],
    size: '10.5', brand: 'Nike', condition: 'like_new',
    priceRange: 2, likes: 267, views: 1640, sold: false,
  },
  {
    sellerId: 'seed_u42', sellerName: S['seed_u42'],
    title: 'Converse Chuck 70 Hi — Parchment 9',
    description: 'Chuck 70 construction, parchment off-white. Worn a handful of times.',
    price: 62,
    images: [IMGS.shoes[4]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['vintage', 'casual', 'minimal'], colors: ['cream', 'off-white'],
    size: '9', brand: 'Converse', condition: 'good',
    priceRange: 1, likes: 201, views: 1230, sold: false,
  },
  {
    sellerId: 'seed_u21', sellerName: S['seed_u21'],
    title: 'New Balance 574 Legacy — Grey/White 10',
    description: 'Classic 574 in grey/white colourway. Size 10. One month of light wear.',
    price: 72,
    images: [IMGS.shoes[0]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['minimal', 'casual'], colors: ['grey', 'white'],
    size: '10', brand: 'New Balance', condition: 'like_new',
    priceRange: 1, likes: 168, views: 1020, sold: false,
  },
  {
    sellerId: 'seed_u43', sellerName: S['seed_u43'],
    title: 'Reebok Club C 85 — White/Green 9',
    description: 'Clean Club C. White leather upper, green Reebok vector. Deadstock.',
    price: 55,
    images: [IMGS.shoes[4]],
    category: 'shoes', subcategory: 'sneakers',
    styles: ['minimal', 'classic', 'vintage'], colors: ['white', 'green'],
    size: '9', brand: 'Reebok', condition: 'new',
    priceRange: 1, likes: 143, views: 870, sold: false,
  },

  // ── Accessories & More ────────────────────────────────────────────────────
  {
    sellerId: 'seed_u30', sellerName: S['seed_u30'],
    title: 'Oakley Frogskins — Polished Black/Dark Grey Lens',
    description: 'Classic Frogskins frame. Dark grey Prizm lens. One scratch on frame only.',
    price: 62,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'sunglasses',
    styles: ['streetwear', 'outdoor', 'vintage'], colors: ['black'],
    size: 'one size', brand: 'Oakley', condition: 'good',
    priceRange: 1, likes: 188, views: 1140, sold: false,
  },
  {
    sellerId: 'seed_u05', sellerName: S['seed_u05'],
    title: 'Herschel Little America Backpack — Black 25L',
    description: 'Signature stripe lining, laptop sleeve, fleece-lined pocket. Barely used.',
    price: 48,
    images: [IMGS.accessories[2]],
    category: 'accessories', subcategory: 'bags',
    styles: ['outdoor', 'casual', 'preppy'], colors: ['black'],
    size: 'one size', brand: 'Herschel', condition: 'like_new',
    priceRange: 0, likes: 122, views: 740, sold: false,
  },
  {
    sellerId: 'seed_u26', sellerName: S['seed_u26'],
    title: 'Coach Tabby Shoulder Bag 26 — Chalk',
    description: 'Pebbled leather, Coach Horse and Carriage turnlock. Chalk white. Near-perfect.',
    price: 295,
    images: [IMGS.accessories[1]],
    category: 'accessories', subcategory: 'bags',
    styles: ['luxury', 'preppy', 'minimal'], colors: ['white', 'chalk'],
    size: 'one size', brand: 'Coach', condition: 'like_new',
    priceRange: 3, likes: 378, views: 2340, sold: false,
  },
  {
    sellerId: 'seed_u30', sellerName: S['seed_u30'],
    title: 'Fossil Grant Chronograph Watch — Brown Leather',
    description: '44mm case, quartz chrono movement, brown strap. Great entry-level dress watch.',
    price: 88,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'watches',
    styles: ['preppy', 'classic', 'minimal'], colors: ['brown', 'tan'],
    size: 'one size', brand: 'Fossil', condition: 'good',
    priceRange: 1, likes: 112, views: 680, sold: false,
  },
  {
    sellerId: 'seed_u26', sellerName: S['seed_u26'],
    title: 'Longchamp Le Pliage Tote M — Navy',
    description: 'The classic foldable tote. Navy nylon, leather handles. Very good condition.',
    price: 68,
    images: [IMGS.accessories[3]],
    category: 'accessories', subcategory: 'bags',
    styles: ['preppy', 'casual', 'minimal'], colors: ['navy'],
    size: 'one size', brand: 'Longchamp', condition: 'good',
    priceRange: 1, likes: 201, views: 1230, sold: false,
  },
  {
    sellerId: 'seed_u29', sellerName: S['seed_u29'],
    title: 'Ray-Ban Wayfarer Classic — Black/G-15 50mm',
    description: 'Original Ray-Ban Wayfarer. Black acetate, G-15 classic green lens. No scratches.',
    price: 78,
    images: [IMGS.accessories[0]],
    category: 'accessories', subcategory: 'sunglasses',
    styles: ['vintage', 'classic', 'preppy'], colors: ['black', 'green'],
    size: 'one size', brand: 'Ray-Ban', condition: 'like_new',
    priceRange: 1, likes: 167, views: 1010, sold: false,
  },
  {
    sellerId: 'seed_u45', sellerName: S['seed_u45'],
    title: 'Porter Tanker Brief Case — Olive OS',
    description: 'Yoshida & Co. Tanker nylon. All zips function. One of the best utility bags made.',
    price: 185,
    images: [IMGS.accessories[2]],
    category: 'accessories', subcategory: 'bags',
    styles: ['japanese', 'minimal', 'outdoor'], colors: ['olive', 'green'],
    size: 'one size', brand: 'Porter', condition: 'good',
    priceRange: 3, likes: 244, views: 1490, sold: false,
  },
];

// ─── Exports ──────────────────────────────────────────────────────────────────

export function getSeedItems(): Item[] {
  const now = Date.now();
  return items.map((data, i) => ({
    ...data,
    id: `seed_item_${String(i + 1).padStart(3, '0')}`,
    createdAt: now - i * 3_600_000, // stagger items 1 h apart
  }));
}

export function getSeedUsers(): UserProfile[] {
  const now = Date.now();
  return SEED_SELLERS.map((s, i) => ({
    id: s.id,
    name: s.name,
    avatar: s.avatar,
    bio: s.bio,
    createdAt: now - (i + 1) * 86_400_000, // stagger sign-ups over 50 days
    totalLikes: 0,
    totalListings: 0,
    isPremium: false,
  }));
}
